# -*- coding: utf-8 -*-
"""Deep learnig regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cZ03mxa3-q_3QTjZAIwxHrs7nitcYgO-
"""

import tensorflow as tf

import seaborn

df = seaborn.load_dataset('tips')

df

df.dtypes

df.isnull().sum()

df['sex'].unique()

sex_dict = { 'Male':1, 'Female':0 }

df['sex'] = df['sex'].map(sex_dict)

df['sex'].dtypes

df.dtypes

df['smoker'].unique()

smoke_dict = { 'Yes':1, 'No':0 }

df['smoker'] = df['smoker'].map(smoke_dict)

df.dtypes

df['day'].unique()

day_dict = {'Sun':1, 'Sat':2, 'Thur':3, 'Fri':4 }

df['day'] = df['day'].map(day_dict)

df.dtypes

df['time'].unique()

time_dict = {'Dinner':1, 'Lunch':0 }

df['time'] = df['time'].map(time_dict)

df.dtypes

df.head()

type(df['smoker'][0])

input_col = df.drop('tip',axis=1)

input_col.head()

output_col = df['tip']

output_col.head()

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense

model = Sequential()

l1 = Dense(120)
l2 = Dense(200)
l3 = Dense(280)
l4 = Dense(350)
l5 = Dense(400)
l6 = Dense(500)
l7 = Dense(500)
l8 = Dense(1)

model.add(l1)
model.add(l2)
model.add(l3)
model.add(l4)
model.add(l5)
model.add(l6)
model.add(l8)
model.add(l7)

model.compile(loss='mean_squared_error')

model.fit(input_col,output_col,epochs=300)

# l1.get_weights()

# l4.get_weights()

model.predict([[24.59,0,0,1,1,4]])

df.head()